services:
  - type: web
    name: aspiro-ai
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    healthCheckPath: "/health"
    envVars:
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false 